export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#514538",
        "on-tertiary-fixed-variant": "#474744",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2e1",
        "surface-container-highest": "#e4e2e1",
        "secondary-fixed": "#f3dfce",
        "tertiary-fixed-dim": "#c8c6c2",
        "surface-container-high": "#eae7e7",
        "inverse-surface": "#303030",
        "on-tertiary-fixed": "#1b1c19",
        "on-secondary-container": "#706254",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "on-surface": "#1b1c1c",
        "on-error": "#ffffff",
        "surface-bright": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#e4e2dd",
        "outline-variant": "#bfc9c5",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3f4946",
        "surface-container": "#f0eded",
        surface: "#fcf9f8",
        tertiary: "#2c2c29",
        "primary-fixed-dim": "#95d3c4",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed-variant": "#095045",
        "surface-tint": "#2b685c",
        "on-primary-fixed": "#00201b",
        "secondary-container": "#f3dfce",
        "surface-container-lowest": "#ffffff",
        primary: "#00322a",
        "tertiary-container": "#42423f",
        "on-secondary": "#ffffff",
        "primary-fixed": "#b0efdf",
        "on-primary-container": "#7dbaab",
        "primary-container": "#004b40",
        "on-secondary-fixed": "#231a0f",
        "inverse-on-surface": "#f3f0f0",
        "inverse-primary": "#95d3c4",
        secondary: "#6a5c4e",
        "on-background": "#1b1c1c",
        outline: "#707976",
        "secondary-fixed-dim": "#d6c3b3",
        background: "#fcf9f8",
        "on-tertiary-container": "#afaeaa",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "120px",
        "container-max": "1200px",
        unit: "8px",
        gutter: "24px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        body: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 10px 40px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
};
